version: 0.1.{build}
skip_non_tags: true

before_build:
- cmd: dotnet.exe restorebuild:
  verbosity: minimal

test:
  assemblies:
  - test\Myvas.AspNetCore.Tests\bin\Debug\netcoreapp1.1\Myvas.AspNetCore.dll

notifications:
- provider: Email
  to:
  - 4848285@qq.com
  subject: Notification from ci.appveyor.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true