version: 0.1.{build}
before_build:
- cmd: dotnet.exe restore
build:
  verbosity: minimal
test:
  assemblies: '**\*.tests.dll'
notifications:
- provider: Email
  to:
  - 4848285@qq.com
  subject: Notification from ci.appveyor.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true