version: 0.1.{build}
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: dotnet.exe restore
build:
  verbosity: minimal
test: off
deploy: off
notifications:
- provider: Email
  to:
  - 4848285@qq.com
  subject: Notification from ci.appveyor.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true